# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DamengPlugin
                                 A QGIS plugin
 -TODO:Link to Dameng and import spatail data into the database
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-16
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Dameng
        email                : yangzhenyu@dameng.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import qgis
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QDialog

from . import async_util

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .damengplugin_dialog import DamengPluginDialog
from .import_dialog import ImportDialog
import os.path
import sys


class DamengPlugin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'DamengPlugin_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&DamengPlugin')

        self.pluginIsActive = False
        self.dlg = None

        self.damengplugin_dialog = None
        self.import_dialog = None
        self.conn_params = {}
        self.libs_dir = os.path.join(self.plugin_dir, 'libs')
        if self.libs_dir not in sys.path:
            sys.path.insert(0, self.libs_dir)


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('DamengPlugin', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/damengplugin/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'DM to QGIS'),
            callback=self.run,
            parent=self.iface.mainWindow())

        #self.loop = async_util.create_loop()


    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dlg is closed"""

        # disconnects
        self.dlg.closingPlugin.disconnect(self.onClosePlugin)

        self.pluginIsActive = False


    def unload(self):
        #async_util.stop_loop(self.loop)
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginDatabaseMenu(
                self.tr(u'&DM to QGIS'),
                action)
            self.iface.removeToolBarIcon(action)


    #显示连接页面
    def show_connect_page(self):
        if not self.damengplugin_dialog:
            self.damengplugin_dialog = DamengPluginDialog(self)
        #填充已保存的数据
        self.damengplugin_dialog.fill_params(self.conn_params)
        self.damengplugin_dialog.show()
        

    #显示导入页面
    def show_import_page(self):
        if not self.import_dialog:
            self.import_dialog = ImportDialog(self, self.damengplugin_dialog.conn)
        self.import_dialog.show()


    def quit_plugin(self):
        self.conn_params = {}
        if self.damengplugin_dialog:
            if self.damengplugin_dialog.conn:
                self.damengplugin_dialog.conn.close()
            self.damengplugin_dialog.destroy()
            self.damengplugin_dialog = None
        if self.import_dialog:
            if self.import_dialog.cursor:
                self.import_dialog.cursor.close()
            self.import_dialog.destroy()
            self.import_dialog = None


    def run(self):
        """Run method that performs all the real work"""
        self.show_connect_page()