# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connect.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(415, 272)
        self.lineEditHost = QtWidgets.QLineEdit(Dialog)
        self.lineEditHost.setGeometry(QtCore.QRect(130, 20, 251, 21))
        self.lineEditHost.setObjectName("lineEditHost")
        self.lineEditUsername = QtWidgets.QLineEdit(Dialog)
        self.lineEditUsername.setGeometry(QtCore.QRect(130, 120, 251, 21))
        self.lineEditUsername.setText("")
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.lineEditPassword = QtWidgets.QLineEdit(Dialog)
        self.lineEditPassword.setGeometry(QtCore.QRect(130, 170, 251, 21))
        self.lineEditPassword.setInputMask("")
        self.lineEditPassword.setText("")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.userText = QtWidgets.QLabel(Dialog)
        self.userText.setGeometry(QtCore.QRect(20, 120, 101, 16))
        self.userText.setObjectName("userText")
        self.ipText = QtWidgets.QLabel(Dialog)
        self.ipText.setGeometry(QtCore.QRect(20, 20, 111, 16))
        self.ipText.setObjectName("ipText")
        self.passwdText = QtWidgets.QLabel(Dialog)
        self.passwdText.setGeometry(QtCore.QRect(20, 170, 101, 16))
        self.passwdText.setObjectName("passwdText")
        self.portText = QtWidgets.QLabel(Dialog)
        self.portText.setGeometry(QtCore.QRect(20, 70, 81, 16))
        self.portText.setObjectName("portText")
        self.ConnectButton = QtWidgets.QPushButton(Dialog)
        self.ConnectButton.setGeometry(QtCore.QRect(150, 220, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConnectButton.sizePolicy().hasHeightForWidth())
        self.ConnectButton.setSizePolicy(sizePolicy)
        self.ConnectButton.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.ConnectButton.setObjectName("ConnectButton")
        self.TestConnectButton = QtWidgets.QPushButton(Dialog)
        self.TestConnectButton.setGeometry(QtCore.QRect(20, 220, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TestConnectButton.sizePolicy().hasHeightForWidth())
        self.TestConnectButton.setSizePolicy(sizePolicy)
        self.TestConnectButton.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.TestConnectButton.setObjectName("TestConnectButton")
        self.QuitButton = QtWidgets.QPushButton(Dialog)
        self.QuitButton.setGeometry(QtCore.QRect(280, 220, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QuitButton.sizePolicy().hasHeightForWidth())
        self.QuitButton.setSizePolicy(sizePolicy)
        self.QuitButton.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.QuitButton.setObjectName("QuitButton")
        self.lineEditPort = QtWidgets.QLineEdit(Dialog)
        self.lineEditPort.setGeometry(QtCore.QRect(130, 70, 251, 21))
        self.lineEditPort.setObjectName("lineEditPort")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Connect to DM"))
        self.lineEditHost.setText(_translate("Dialog", "localhost"))
        self.userText.setText(_translate("Dialog", "Username:"))
        self.ipText.setText(_translate("Dialog", "Server IP:"))
        self.passwdText.setText(_translate("Dialog", "Password:"))
        self.portText.setText(_translate("Dialog", "Port:"))
        self.ConnectButton.setAccessibleDescription(_translate("Dialog", "Connect to the server"))
        self.ConnectButton.setText(_translate("Dialog", "Connect"))
        self.TestConnectButton.setAccessibleDescription(_translate("Dialog", "Test connect to the server"))
        self.TestConnectButton.setText(_translate("Dialog", "Test"))
        self.QuitButton.setAccessibleDescription(_translate("Dialog", "Quit"))
        self.QuitButton.setText(_translate("Dialog", "Quit"))
        self.lineEditPort.setText(_translate("Dialog", "5236"))
